package kotlinx.coroutines.internal;

public final class ExceptionSuccessfullyProcessed extends Exception {

    /* renamed from: b  reason: collision with root package name */
    public static final ExceptionSuccessfullyProcessed f40734b = new ExceptionSuccessfullyProcessed();

    private ExceptionSuccessfullyProcessed() {
    }
}
